version: '3'

services:

  php-fpm:
    container_name: php-fpm
    build:
      context: "../"
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../../backend:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root@mariadb:3306/todo"
      PHP_IDE_CONFIG: serverName=localhost
      SLACK_SIGNING_SECRET: secret

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
