apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.app.name }}
    service: nginx
    branch: {{ .Values.ci.branch.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: cf-dns
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: {{ .Values.app.url }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.nginx.name }}
              servicePort: 80
            path: /
  tls:
    - hosts:
      - {{ .Values.app.url }}
      secretName: "{{ .Values.app.url }}-tls"
