apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.app.name }}
    service: nginx
    branch: {{ .Values.ci.branch.name }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.app.name }}
    service: nginx
    branch: {{ .Values.ci.branch.name }}
  clusterIP: None
