apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.php.name }}
  labels:
    app: {{ .Values.app.name }}
    service: php-fpm
    branch: {{ .Values.ci.branch.name }}
spec:
  ports:
    - port: 9000
  selector:
    app: {{ .Values.app.name }}
    service: php-fpm
    branch: {{ .Values.ci.branch.name }}
  clusterIP: None
