services:
    Monolog\Formatter\JsonFormatter: ~

monolog:
    handlers:
        stdout:
            type: stream
            path: "php://stdout"
            level: info
            formatter: Monolog\Formatter\JsonFormatter
